### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by mzarowka** [mzarowka/hsitools-paper#1]
- [ ] HSItools is published and available with no problems.
- [ ] Manuscript.
- [ ] Figures.
- [ ] Authors' input and final agreement.
- [ ] Authors' credits.
- [ ] Acknowledgements and founding.
- [ ] Accompanying code.
- [ ] Journal choice.
